model:
  model_name: "dslim/bert-base-NER"

hyperparameters:
  learning_rate: 2e-5
  num_train_epochs: 10
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0.01
  save_total_limit: 3
  logging_steps: 100
  metric_for_best_model: "f1"
  greater_is_better: true
  evaluation_strategy: "epoch"
  logging_strategy: "steps"
  save_strategy: "epoch"
  load_best_model_at_end: true

labels:
  id2label: {0: "O", 1: "B-Mountain", 2: "I-Mountain"}
  label2id: {"O": 0, "B-Mountain": 1, "I-Mountain": 2}

hf:
  data_path: "telord/ner-mountains-dataset"
  save_model_path : "telord/ner-mountains-model"
